# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db74ab4f4650732474341cb3c5b0271b61f999ab463d27c3220f91d9d72fc0fe48a4a08b41abe40d3be6bdccff8a25f6aa54e894fd69251cd581bff03c4852fc

test:
  secret_key_base: 46d87be8f76ec865cb900b04623253f71b9df8ac1624a8fc87b1c2b01aef3aabd642137d84b97c7f3a58d301e36f8b666822f8dfd5d3a67641a2f2aed01dee79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
